### ISSUE TITLE
unable to seed project

### ISSUE THREAD

**Issue by Kaleygill** [meaghanlewis/stickerfy#17]
error received: 
$ node seed/product-seeder.js
(node:8976) UnhandledPromiseRejectionWarning: MongooseError: The `uri` parameter
 to `openUri()` must be a string, got "undefined". Make sure the first parameter
 to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (D:\Projects\stickerfy\node_modules\m
ongoose\lib\connection.js:694:11)
    at D:\Projects\stickerfy\node_modules\mongoose\lib\index.js:351:10
    at D:\Projects\stickerfy\node_modules\mongoose\lib\helpers\promiseOrCallback
.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (D:\Projects\stickerfy\node_modules\mongoose\lib\helper
s\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (D:\Projects\stickerfy\node_modules\mongoose\
lib\index.js:1149:10)
    at Mongoose.connect (D:\Projects\stickerfy\node_modules\mongoose\lib\index.j
s:350:20)
    at Object.<anonymous> (D:\Projects\stickerfy\seed\product-seeder.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js
:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8976) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 1)
(node:8976) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by meaghanlewis** [comment]
@Kaleygill I am working on fixing this problem! Sorry for the trouble. Will update this issue once the seed error is resolved.

**Comment by meaghanlewis** [comment]
This issue should have been resolved in: https://github.com/meaghanlewis/stickerfy/pull/18
